=== tinganho/LYA/src/core/dtd/folders.dtd
<!ELEMENT Folders (Folder*)>
<!ELEMENT Folder (Description?, Image?, Folders?)>
<!ATTLIST Folder name ID #REQUIRED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Image (#PCDATA)>
<!ATTLIST Image src CDATA #REQUIRED>

=== tinganho/LYA/src/dtd/references/folders.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Folders SYSTEM "../folders.dtd">
<Folders>
    <Folder name="SignUp">
        <Description>Signup view</Description>
        <Image src="wmiewfmemwew"></Image>
        <Folders>
            <Folder name="SignUp3">
                <Description>Signup view</Description>
                <Image src="wmiewfmemwew"></Image>
            </Folder>
        </Folders>
    </Folder>
    <Folder name="SignUp2">
        <Description>Signup view</Description>
        <Image src="wmiewfmemwew"></Image>
    </Folder>
</Folders>
