=== tinganho/LYA/src/core/dtd/localizations.dtd
<!ELEMENT Localizations (Localization*)>
<!ATTLIST Localizations language CDATA #REQUIRED>

<!ELEMENT Localization (Message, Parameters, Files, Timestamp, Comment?)>
<!ATTLIST Localization id ID #REQUIRED>

<!ELEMENT Message (#PCDATA)>

<!ELEMENT Parameters (Parameter*)>
<!ELEMENT Parameter (Type)>
<!ATTLIST Parameter name ID #REQUIRED>

<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type language CDATA #REQUIRED>

<!ELEMENT Files (File)>
<!ELEMENT File (#PCDATA)>
<!ATTLIST File language CDATA #REQUIRED>

<!ELEMENT Timestamp (#PCDATA)>

<!ELEMENT Comment (#PCDATA)>

=== tinganho/LYA/src/core/dtd/examples/localizations.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Localizations SYSTEM "../localizations.dtd">
<Localizations language="en-US">
    <Localization id="LogIn__SignUp__FirstName">
        <Message>Please signup here {markup, html, {name}}.</Message>
        <Parameters>
            <Parameter name="name">
                <Type language="TypeScript">string</Type>
            </Parameter>
            <Parameter name="age">
                <Type language="TypeScript">number</Type>
            </Parameter>
        </Parameters>
        <Files>
            <File language="TypeScript">src/app/home_page.ts</File>
        </Files>
        <Timestamp>2017-10-31T20:21:23Z</Timestamp>
        <Comment>Signup field.</Comment>
    </Localization>
</Localizations>
